version: '3.9'
services:
  mock:
    build:
      context: ./mock/server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on: mysql
  mysql:
    platform: linux/x86_64
    image: mysql:8-debian
    restart: always
    environment:
      MYSQL_DATABASE: 'humservice'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'goaplication'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'goIsKing'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin1234'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: