version: '3.9'
services:
  server:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MYSQL_STRING: 'goaplication:goIsKing@tcp(mysql:3306)/humservice?parseTime=true'
      CRON_INTERVAL: '@every 10m'
    depends_on: 
      mysql:
        condition: service_healthy
    # networks:
    #   - backend

  mysql:
    platform: linux/x86_64
    image: mysql:8-debian
    restart: always
    environment:
      MYSQL_DATABASE: 'humservice'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'goaplication'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'goIsKing'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'admin1234'
      SSL-MODE: 'DISABLED' 
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./liveDB:/var/lib/mysql
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    # networks:
    #   - backend

# networks:
#   backend:
#       driver: bridge